### ISSUE TITLE
Windguru default model

### ISSUE THREAD

**Issue by stefano-gentile** [jeroentvb/wind-scrape#49]
Hey! Amazing app. I'm, trying to retrieve the default model which appairs at first, is that possible?

Thanks

**Comment by jeroentvb** [comment]
> I'm, trying to retrieve the default model which appairs at first

I'm assuming you mean the 'WG' model. Scraping that model is currently not possible with wind-scrape, because it uses [windguru micro](http://micro.windguru.cz/help.php), and windguru micro doesn't include the WG model. All currently scrapable models are listed on the windguru micro [help page](http://micro.windguru.cz/help.php).

Wind-scrape uses  windguru micro because it serves static html pages which make scraping a lot faster and easier. The normal website dynamically loads content, so one would need to use a headless browser to wait for the content to load and then scrape, instead of simply fetching a html file.

It is certainly possible to scrape the WG model, but would require the use of a headless browser, to:
1. Log in (otherwise you don't get the personalized model values)
2. Wait for the content to load and scrape it

So while it is possible, it's quite a bit of work to build the feature. I'm currently not interested in building it. You're welcome to submit a PR.

**Comment by stefano-gentile** [comment]
Thanks for that detailed explanation. I didn't know about those requisites to scrape the WG model, currently I'm in a learning curve, I don't have enough knowledge to do that, but for a future project. 

Thank you for your time!
