### ISSUE TITLE
Error in typescript

### ISSUE THREAD

**Issue by Celinium** [jeroentvb/wind-scrape#52]
Hello,

I installed wind-srape v4.1.4 on a Raspberry Pi using this command line:
xxx@raspberrypi:~/hass $ npm install https://github.com/jeroentvb/wind-scrape/releases/download/v4.1.4/dist.tgz

I created this wind-scrap.ts :
`const scrape = require('wind-scrape')
// TypeScript
import * as scrape from 'wind-scrape'
// Scrape windfinder spot
scrape.windfinder('tarifa')`

When running tsc wind-scrap.ts I get the follwing 2 errors  :
wind-scrap.ts:1:7 - error TS2440: Import declaration conflicts with local declaration of 'scrape'.

1 const scrape = require('wind-scrape')
        ~~~~~~
wind-scrap.ts:4:13 - error TS2440: Import declaration conflicts with local declaration of 'scrape'.

4 import * as scrape from 'wind-scrape'
              ~~~~~~
Found 2 errors in the same file, starting at: wind-scrap.ts:1

Any help? How can I confirm wind-scrap is correctly installed?

Thanks in advance for your support

**Comment by jeroentvb** [comment]
The error is caused by declaring the `scrape` variable 2 times. First by using `const scrape = require('wind-scrape')`, and the second by using `import * as scrape from 'wind-scrape'`.

Since you're using typescript, you should import wind-scrape using `import * as scrape from 'wind-scrape'`.
Removing `const scrape = require('wind-scrape')` from your code should fix the compiler error.

**Comment by Celinium** [comment]
Excellent. With this instruction, it's working now. 
Thank you **jeroentvb** for the script and for the great/quick support.
